version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Test
          command: node test..js

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
